name: project_name

on:
  - pull_request
  - push

env:
  runs-on: ubuntu-latest
  BUILD_TYPE: Debug

jobs:
  Initialize-dependenies:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - name: "Configurating dependencies"
        run: |
          sudo apt install apt-transport-https curl gnupg -y 
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install bazel
          sudo apt install default-jdk
      

      - uses: actions/checkout@v4

      - name: Build
        run: "bazel build //..."

